; [pytest]
; DJANGO_SETTINGS_MODULE = pytestProjet.settings
; django_find_project = true

[pytest]
# Recherche de fichiers qui correspondent à ces modèles
python_files = test_*.py *_test.py

# Recherche de fonctions qui correspondent à ces modèles
python_functions = test_*

# Recherche de classes de test qui correspondent à ces modèles
python_classes = Test*

# Exclure les répertoires ou fichiers spécifiques de la recherche de tests
norecursedirs = .git dist build *.egg-info

# Options supplémentaires
addopts = -ra -q